# Generated by Django 5.1.3 on 2024-12-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0005_idea'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='market_opportunity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='target_audience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='category',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Finance', 'Finance'), ('Health', 'Health'), ('Entertainment', 'Entertainment'), ('Food', 'Food')], default='Tech', max_length=100),
        ),
    ]
