# Generated by Django 5.1.3 on 2024-12-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0009_remove_profile_twitter_profile_twitjter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='twitjter',
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
