# Generated by Django 5.1.3 on 2024-12-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0013_alter_comment_downvotes_alter_comment_upvotes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
