# Generated by Django 5.1.3 on 2025-01-30 15:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0016_acknowledgment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='content',
            field=models.TextField(default='No feedback provided'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='feedback',
            name='idea',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='incubator.idea'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='mentor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
